### ISSUE TITLE
login not working anymore.

### ISSUE THREAD

**Issue by maxemanZ** [iamtalhaasghar/spotify-streaming-bot#1]
spotify has a fix for automation now that blocks selenium, now logging in doesnt work anymore.

**Comment by iamtalhaasghar** [comment]
Ok, i will check it.

**Comment by iamtalhaasghar** [comment]
The login is working fine. You can check the following screenshot. I am closing this issue for now. Feel free to open it again if you want to discuss it further.

![Screenshot_2021-05-29_10-08-16](https://user-images.githubusercontent.com/46928648/120058657-118dab80-c03c-11eb-8a3a-30cc3428aa33.png)
