### ISSUE TITLE
It is not playing 

### ISSUE THREAD

**Issue by alansenairj** [iamtalhaasghar/spotify-streaming-bot#2]
Webdriver is OK
Login is ok

but it parses this element: 

"<button class= (omitted quotes ")
_8e7d398e09c25b24232d92aac8a15a81-scss e8b2fe03d4e4726484b879ed8ff6f096-scss" aria-label="Play" data-testid="play-button" style="--size:56px;">flex"

It can find that id but it is not working and doing any clicks. 

DevTools listening on ws://127.0.0.1:53587/devtools/browser/4171ab28-dbd0-4e9e-9767-8eee9af6e92d
clicking play button #  0
clicking play button #  1

#nothing happened 

the actual xpath is: 
//*[@id="main"]/div/div[2]/div[3]/main/div[2]/div[2]/div/div/div[2]/section/div[2]/div[2]/div/button[1]

Any clue?

**Comment by iamtalhaasghar** [comment]
While debugging, I found following issues in Developer Console while running Spotify with selenium. I think they are trying to avoid bots by enforcing these policies.
# Issues
1. Content Security Policy of your site blocks the use of 'eval' in JavaScript`
The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.
To solve this issue, avoid using eval(), new Function(), setTimeout([string], ...) and setInterval([string], ...) for evaluating strings.
If you absolutely must: you can enable string evaluation by adding unsafe-eval as an allowed source in a script-src directive.
⚠️ Allowing string evaluation comes at the risk of inline script injection.
1 directive
Source Location	Directive	Status
vendor~web-player.4f814f36.js:1	script-src	blocked
Learn more: Content Security Policy - Eval

2. SharedArrayBuffer usage is restricted to cross-origin isolated sites
SharedArrayBuffers (SABs) can be used to construct high-resolution timers. High-resolution timers simplify Spectre attacks on cross-origin resources.
To mitigate security risks across browsers, SharedArrayBuffers are gated behind cross-origin isolated contexts starting with Chrome 91 (May 2021). To continue using SharedArrayBuffers, please ensure that this page opts-into cross-origin isolation by setting Cross-Origin-Opener-Policy and Cross-Origin-Embedder-Policy appropriately.
Note that for each iframe, only the first issue is reported for performance reasons.
1 violation
Source Location	Trigger	Status
vendor~web-player.4f814f36.js:1	Instantiation	warning
